AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  liveadhocMediaLive:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: live.handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::394761604539:role/live-adhoc-MediaLiveFuncRole-NCEJ08ZH6X0E'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: '/{channelname}/{opt}'
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: '/{channelname}/{opt}'
            Method: GET
      Environment:
        Variables:
          MediaLiveRoleARN: 'arn:aws:iam::394761604539:role/live-adhoc-MediaLiveRole-FCP8X2OZ33N4'
      Tags:
        'lambda:createdBy': SAM
