AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  liveadhocLiveAdhocState:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: state.handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: >-
        arn:aws:iam::394761604539:role/live-adhoc-LiveAdhocStateFuncRole-71YX6GZRZUVK
      Environment:
        Variables:
          DynamoDBMediaLiveName: live-adhoc-MediaLiveState
          DynamoDBWowName: live-adhoc
      Tags:
        'lambda:createdBy': SAM
