AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  liveadhocLiveAdhocProvision:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: provision.handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: >-
        arn:aws:iam::394761604539:role/live-adhoc-LiveAdhocProvisionFuncRole-QM4OKKAEKCJH
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /adhoc/create
            Method: POST
      Environment:
        Variables:
          MediaLiveRoleARN: 'arn:aws:iam::394761604539:role/live-adhoc-MediaLiveRole-FCP8X2OZ33N4'
          TokenFunctionArn: >-
            arn:aws:lambda:ap-southeast-2:394761604539:function:cloud9-telstraWowzaLiveToken-telstraWowzaLiveToken-5VF247PEJKOZ
      Tags:
        'lambda:createdBy': SAM
