AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  liveadhocWowzaScan:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: scan.handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: >-
        arn:aws:iam::394761604539:role/live-adhoc-WowzaScanFuncRole-13B8Q8IVJZ3YN
      VpcConfig:
        SecurityGroupIds:
          - sg-08b24fac3c12f7c8b
        SubnetIds:
          - subnet-0d56d885ceb818bee
          - subnet-03aaf4a0e7b7bf1af
          - subnet-0bc04b75b336401dc
      Environment:
        Variables:
          DynamonDBName: live-adhoc
      Tags:
        'lambda:createdBy': SAM
