AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  sportvodapimediaConvertJobCreationFunction1MG6BAVL200UC:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: convert.handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: >-
        arn:aws:iam::394761604539:role/sportvodapi-mediaConvertJobRole-PQNE9FUJMTQT
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /vodconvert/jobs
            Method: POST
      Environment:
        Variables:
          EndPoint_url: 'https://wvttkmhib.mediaconvert.ap-southeast-2.amazonaws.com'
          JobTemplateARN: 'arn:aws:mediaconvert:ap-southeast-2:394761604539:jobTemplates'
      Tags:
        'lambda:createdBy': SAM
