AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  telstravodpackageassetdeletionapi:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: package.handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::394761604539:role/telstra_vod_lambda_role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /vodpackage/assetdeletion
            Method: POST
