AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Stream events from AWS CloudWatch Logs to Splunk's HTTP event collector
Resources:
  telstrasplunkforwardervodpackage:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: Stream events from AWS CloudWatch Logs to Splunk's HTTP event collector
      MemorySize: 512
      Timeout: 10
      Role: 'arn:aws:iam::394761604539:role/telstra_splunk_forwarder_role'
      VpcConfig:
        SecurityGroupIds:
          - sg-06745aa53f9877247
        SubnetIds:
          - subnet-0d56d885ceb818bee
          - subnet-03aaf4a0e7b7bf1af
          - subnet-0bc04b75b336401dc
      Environment:
        Variables:
          SPLUNK_HEC_TOKEN: test
          SPLUNK_HEC_URL: test
      Tags:
        'lambda-console:blueprint': splunk-cloudwatch-logs-processor
