AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  cloud9telstraWowzaLiveTokentelstraWowzaLiveToken5VF247PEJKOZ:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: telstraWowzaLiveToken/lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::394761604539:role/telstra_lambda_wow_live'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /token/validate
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: /token/validate
            Method: POST
        Api3:
          Type: Api
          Properties:
            Path: /token/create
            Method: POST
        Api4:
          Type: Api
          Properties:
            Path: /token/validate
            Method: POST
        Api5:
          Type: Api
          Properties:
            Path: /token/read
            Method: POST
        Api6:
          Type: Api
          Properties:
            Path: /token/read
            Method: POST
        Api7:
          Type: Api
          Properties:
            Path: /token/create
            Method: POST
      Tags:
        'lambda:createdBy': SAM
